version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobsearch_db
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
